stages:
  - build
  - test
  - deploy

variables:
  # Define global environment variables
  PROJECT_NAME: "example-project"

build-job:
  stage: build
  script:
    - echo "Building the project..."
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 hour

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - npm test
  dependencies:
    - build-job

deploy-job:
  stage: deploy
  script:
    - echo "Deploying the project..."
    - npm run deploy
  only:
    - main
